name: Unit Tests

on: [push]

jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-java@v2
              with:
                java-version: 3.8

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run tests
              run: |
                python -m unittest discover -s tests -p "*_test.py"