name: Unit Tests

on: [push]

jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                java-version: '11'
                distribution: 'adopt'

            - name: Run tests
              run: |
                mvn -q test